<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:hr="http://ns.hr-xml.org/2007-04-15"
	xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:soapenc11="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:tns="http://ns.setu.nl/SETUWebServices/2012-01"
	xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ns.setu.nl/SETUWebServices/2012-01">
	<wsdl:documentation>
		Name: 		Vacancies-ServiceSETU-owner.wsdl
		Purpose: 	specifies the webservices for receiving VacancyResponseNL messages at the owner interface in a Vacancy process.  
		Author(s): 	SETU
		Release: 	SETU Standard for Vacancies v1.0 
		Date: 		2012-12-13
		Last edit:	2020-11-24
	</wsdl:documentation>
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ns.setu.nl/SETUWebServices/2012-01" elementFormDefault="qualified">
			<xsd:import namespace="http://ns.hr-xml.org/2007-04-15" schemaLocation="../../../hr-xml/SEP/VacancyResponseNL.xsd"/>
			<xsd:import namespace="http://ns.hr-xml.org/2007-04-15" schemaLocation="../../../hr-xml/CPO/Acknowledgement.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="ResponseRequest">
		<wsdl:documentation>A generic request of type VacancyResponseNL.</wsdl:documentation>
		<wsdl:part name="input" element="hr:VacancyResponseNL"/>
	</wsdl:message>
	<wsdl:message name="Acknowledgement">
		<wsdl:documentation>A generic response of type Acknowledgement.</wsdl:documentation>
		<wsdl:part name="output" element="hr:Acknowledgement"/>
	</wsdl:message>
	
	<wsdl:portType name="VacancyService">
		<wsdl:operation name="ProcessVacancyResponse">
			<wsdl:documentation>The VacancyResponse operation is used in the Vacancies process, scenarios 'New Vacancy' and 'Other processses/actions'. The request message is a VacancyResponseNL message.</wsdl:documentation>
			<wsdl:input message="tns:ResponseRequest"/>
			<wsdl:output message="tns:Acknowledgement"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="SoapServiceHttpBinding" type="tns:VacancyService">
		<wsdl:documentation>The soapAction value for each operation can be used to indicate the intent of the SOAP request. It enables the receiver to appropriately identify the operation requested.</wsdl:documentation>
		<wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="ProcessVacancyResponse">
			<wsdlsoap:operation soapAction="https://www.organisatie.nl/SETUServicesEndpoint/ProcessVacancyResponse"/>
			<wsdl:input>
				<wsdlsoap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<wsdlsoap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="VacancySoapService">
		<wsdl:port name="SETUServicesEndpoint" binding="tns:SoapServiceHttpBinding">
			<wsdl:documentation>The address location (URL) for the services endpoint of the Vacancy operations can be selected freely.</wsdl:documentation>
			<wsdlsoap:address location="https://www.organisatie.nl/SETUServicesEndpoint"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>