<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:hr="http://ns.hr-xml.org/2007-04-15"
	xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:soapenc11="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:tns="http://ns.setu.nl/SETUWebServices/2014-01"
	xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ns.setu.nl/SETUWebServices/2014-01">
	<wsdl:documentation>
		Name: 		20141216_CV-CurriculumViteaServiceSETU-recipient.wsdl
		Purpose: 	specifies the webservices for receiving CV messages at the recipient interface in the process of exchanging CV messages.
		Author(s): 	SETU
		Release:	SETU Standard for CV v1.0
		Date: 		2014-12-16
		Last edit:	2020-11-24
	</wsdl:documentation>
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ns.setu.nl/SETUWebServices/2014-01" elementFormDefault="qualified">
			<xsd:import namespace="http://ns.hr-xml.org/2007-04-15" schemaLocation="../../../hr-xml/SEP/CandidateNL.xsd"/>
			<xsd:import namespace="http://ns.hr-xml.org/2007-04-15" schemaLocation="../../../hr-xml/CPO/Acknowledgement.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="CVRequest">
		<wsdl:part name="input" element="hr:CandidateNL"/>
	</wsdl:message>
	<wsdl:message name="Acknowledgement">
		<wsdl:part name="output" element="hr:Acknowledgement"/>
	</wsdl:message>
	
	<wsdl:portType name="CurriculumVitaeService">
		<wsdl:operation name="ProcessCV">
			<wsdl:documentation>The request message is a CV message.</wsdl:documentation>
			<wsdl:input message="tns:CVRequest"/>
			<wsdl:output message="tns:Acknowledgement"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="SoapServiceHttpBinding" type="tns:CurriculumVitaeService">
		<wsdl:documentation>The soapAction value for each operation can be used to indicate the intent of the SOAP request. It enables the receiver to appropriately identify the operation requested.</wsdl:documentation>
		<wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="ProcessCV">
			<wsdlsoap:operation soapAction="https://www.setu.nl/SETUWebServices/2014-01/ProcessCV" style="document"/>
			<wsdl:input>
				<wsdlsoap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<wsdlsoap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="CurriculumVitaeSoapService">
		<wsdl:port name="SETUServicesEndpoint" binding="tns:SoapServiceHttpBinding">
			<wsdl:documentation>The address location (URL) for the services endpoint of the Curriculum Vitae Service operations can be selected freely.</wsdl:documentation>
			<wsdlsoap:address location="https://www.organisatie.nl/SETUServicesEndpoint"/>
		</wsdl:port>
	</wsdl:service>	
</wsdl:definitions>