openapi: 3.1.0
info:
  title: Inquiry Pay Equity
  version: 2.0.0-draft.3
  description: |-
    # Models
    ## Inquiry Pay Equity
    <SchemaDefinition schemaRef="#/components/schemas/InquiryPayEquity" />

    ## Condition
    <SchemaDefinition schemaRef="#/components/schemas/condition" />
    
    ## Occurence
    <SchemaDefinition schemaRef="#/components/schemas/occurrence" />
components:
  schemas:
    InquiryPayEquity:
      $ref: ./components/schemas/InquiryPayEquity.yaml
